### PR TITLE
Pull request to master branch

### PR DESCRIPTION
**Pull request by kwizl**
Standup meeting pull request

### CODE REVIEW

**Comment by duducus** [comment]
Good structure and a solid CSS
it looks good
good use of comments and a lot of commits

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
### Hi team!

### Nice job! Project looks! :+1: 

### But first of all let's fix the next problems and we can move on.

* Kindly recommended checking HTML markup with this [validator](https://validator.w3.org/#validate_by_upload)

Now it shows a lot of ERRORs in your project



* Your README.md file should be descriptive, you can use this short [Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) to make this file professional.

### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*

*Happy coding 😄*

**Review by Anna-Myzukina — CHANGES_REQUESTED** [review]
Errors in the HTML file. The readme file is not descriptive.

**Comment by nikasulo** [comment]
# Pull Request under the review by Olusakin Oluwadamilare(TSE)
@oluwadamilareolusakin

**Review by nikasulo — APPROVED** [review]

**Comment by nikasulo** [comment]
# Really great work implementing the required changes and fixing the errors!

You may merge :rocket:.

#### See you at the top @duducus and @FrancisMtambo

**Pull request merged**
